
name: QdrantServer
services:
  qdrant:
    image:
      qdrant/qdrant:latest
    ports:
      - 6334:6334
      - 6333:6333
    volumes:
    - ./qdrant_storage:/qdrant/storage:z

# docker run -p 6333:6333 -p 6334:6334 \
#     -v "$(pwd)/qdrant_storage:/qdrant/storage:z" \
#     qdrant/qdrant